adapters:
  openai: OpenAIAdapter
logger_file: ./log/prompt.log
better_prompt_db: ./db/prompt.db
database:
  docs: postgres://docs:ment@localhost/docs
llms:
  isyscore:
    adapter: openai
    url: http://120.133.75.248:39095/v1/
    api_key: sk-48DAsw-494SY957qd25I2Q
    default_model: qwen3-next
  isyscore_embedding:
    adapter: openai
    url: http://120.133.75.248:39095/v1/
    api_key: sk-48DAsw-494SY957qd25I2Q
    default_model: qwen3-embedding
  isyscore_vision:
    adapter: openai
    url: http://120.133.75.248:39095/v1/
    api_key: sk-48DAsw-494SY957qd25I2Q
    default_model: glm-4.5v
    
  SiliconFlow:
    adapter: openai
    url: https://api.siliconflow.cn/v1/
    api_key: ENV["APIKey"]
    default_model: Qwen/Qwen2.5-7B-Instruct
  llamacpp:
    adapter: openai
    url: http://localhost:8080/    
  ollama:
    adapter: openai
    url: http://localhost:11434/
    default_model: deepseek-r1
  deepseek:
    adapter: openai
    url: https://api.deepseek.com
    api_key: ENV["DSKEY"]
    default_model: deepseek-reasoner
  Aliyun:
    adapter: openai
    url: https://dashscope.aliyuncs.com/compatible-mode/v1/
    api_key: ENV["ALIKEY"]
  shengsuanyun:
    adapter: openai
    url: https://router.shengsuanyun.com/api/v1
    api_key: ENV["SSYKEY"]
default_llm: isyscore
worker_path: "./agents/workers"
template_path: "./agents/templates"
